// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB87228g90hrMKQHuISj5DlKrSoTfag6pY',
    appId: '1:280105861567:web:5e17b9b35b3382cc25e10a',
    messagingSenderId: '280105861567',
    projectId: 'stepandget',
    authDomain: 'stepandget.firebaseapp.com',
    databaseURL: 'https://stepandget-default-rtdb.firebaseio.com',
    storageBucket: 'stepandget.appspot.com',
    measurementId: 'G-6PWCKYGK4J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnfZdB2NfwkjG7VSfdHaoapsHme7hnxcI',
    appId: '1:280105861567:android:5789705bb470e38a25e10a',
    messagingSenderId: '280105861567',
    projectId: 'stepandget',
    databaseURL: 'https://stepandget-default-rtdb.firebaseio.com',
    storageBucket: 'stepandget.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoJ_be71NqXGksjXNn4DKyco9Pvlosnfk',
    appId: '1:280105861567:ios:14ee15fbb4f7d40925e10a',
    messagingSenderId: '280105861567',
    projectId: 'stepandget',
    databaseURL: 'https://stepandget-default-rtdb.firebaseio.com',
    storageBucket: 'stepandget.appspot.com',
    androidClientId: '280105861567-3j8lj2vlsu1k6do5hk5tluj05senbcs7.apps.googleusercontent.com',
    iosClientId: '280105861567-0l10eksu8145ha795u7rovuobgsh6502.apps.googleusercontent.com',
    iosBundleId: 'com.example.stepNGet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoJ_be71NqXGksjXNn4DKyco9Pvlosnfk',
    appId: '1:280105861567:ios:14ee15fbb4f7d40925e10a',
    messagingSenderId: '280105861567',
    projectId: 'stepandget',
    databaseURL: 'https://stepandget-default-rtdb.firebaseio.com',
    storageBucket: 'stepandget.appspot.com',
    androidClientId: '280105861567-3j8lj2vlsu1k6do5hk5tluj05senbcs7.apps.googleusercontent.com',
    iosClientId: '280105861567-0l10eksu8145ha795u7rovuobgsh6502.apps.googleusercontent.com',
    iosBundleId: 'com.example.stepNGet',
  );
}
